# Generated by Django 5.1.4 on 2024-12-13 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmscontent',
            old_name='value',
            new_name='content',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='cmscontent',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='cmscontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmscontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cmscontent',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cmscontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cmscontent',
            unique_together={('key', 'language')},
        ),
    ]
