# Generated by Django 5.0.7 on 2024-12-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_logo_logo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(choices=[('chatbot', 'Chatbot Logo'), ('main', 'Main Logo')], default='main', max_length=30)),
            ],
            options={
                'verbose_name': 'Copyright',
                'verbose_name_plural': 'Copyrights',
            },
        ),
        migrations.RemoveField(
            model_name='cmscontent',
            name='category',
        ),
        migrations.AddField(
            model_name='cmscontent',
            name='query',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cmscontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=10),
        ),
    ]
