# Generated by Django 5.0.7 on 2024-12-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_copyright_remove_cmscontent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyright',
            name='content',
            field=models.CharField(max_length=30),
        ),
    ]
