# Generated by Django 5.1.4 on 2024-12-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_copyright_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmscontent',
            name='query',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
