# Generated by Django 5.1.4 on 2024-12-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cmscontent_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmscontent',
            name='query',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
