# Generated by Django 5.1.4 on 2024-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cmscontent_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmscontent',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords'),
        ),
        migrations.AddIndex(
            model_name='cmscontent',
            index=models.Index(fields=['query'], name='api_cmscont_query_035077_idx'),
        ),
        migrations.AddIndex(
            model_name='cmscontent',
            index=models.Index(fields=['language'], name='api_cmscont_languag_4a6c35_idx'),
        ),
    ]
